// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PencilJoyTests.BddCore.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Equal price and discount value on different steps of order")]
    public partial class EqualPriceAndDiscountValueOnDifferentStepsOfOrderFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Maths.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Equal price and discount value on different steps of order", "\tIn order to compare value on different steps of order\r\n\tAs a customer\r\n\tThe user" +
                    " wants to be able to edit currency for order", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user compares price and currency for a book on the preview page and on the ba" +
            "g page")]
        [NUnit.Framework.CategoryAttribute("comparePriceForABook")]
        [NUnit.Framework.CategoryAttribute("previewPage")]
        [NUnit.Framework.CategoryAttribute("bagPage")]
        public virtual void TheUserComparesPriceAndCurrencyForABookOnThePreviewPageAndOnTheBagPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user compares price and currency for a book on the preview page and on the ba" +
                    "g page", new string[] {
                        "comparePriceForABook",
                        "previewPage",
                        "bagPage"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And("The user is on the preview page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.And("The user gets price and currency for a book from the button \"Order for ..\" on the" +
                    " preview page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("The user clicks the button \"Order for ..\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
 testRunner.And("The user clicks the button \"Next\" on the message page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
 testRunner.When("The user gets price and currency  for the first book on the bag page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 14
 testRunner.Then("The price and currency for a book on the preview page and on the bag page should " +
                    "be equal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user compares price and currency for a book on the bag page and on the checko" +
            "ut page")]
        [NUnit.Framework.CategoryAttribute("comparePriceForABook")]
        [NUnit.Framework.CategoryAttribute("bagPage")]
        [NUnit.Framework.CategoryAttribute("checkoutPage")]
        public virtual void TheUserComparesPriceAndCurrencyForABookOnTheBagPageAndOnTheCheckoutPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user compares price and currency for a book on the bag page and on the checko" +
                    "ut page", new string[] {
                        "comparePriceForABook",
                        "bagPage",
                        "checkoutPage"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 19
 testRunner.And("The user is on the bag page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
 testRunner.And("The user gets price and currency for the first book on the bag page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 21
 testRunner.And("The user clicks the button \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
 testRunner.When("The user gets  price and currency for the first book on the checkout page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 23
 testRunner.Then("The price and currency for a book on the bag page and  on the checkout page shoul" +
                    "d be equal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user compares totalprice and currency for order on the bag page and on the ch" +
            "eckout page")]
        [NUnit.Framework.CategoryAttribute("compareTotalPrice")]
        [NUnit.Framework.CategoryAttribute("bagPage")]
        [NUnit.Framework.CategoryAttribute("checkoutPage")]
        public virtual void TheUserComparesTotalpriceAndCurrencyForOrderOnTheBagPageAndOnTheCheckoutPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user compares totalprice and currency for order on the bag page and on the ch" +
                    "eckout page", new string[] {
                        "compareTotalPrice",
                        "bagPage",
                        "checkoutPage"});
#line 26
this.ScenarioSetup(scenarioInfo);
#line 27
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
 testRunner.And("The user is on the bag page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 29
 testRunner.And("The user gets price and currency for the totalprice on the bag page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 30
 testRunner.And("The user clicks the button \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 31
 testRunner.When("The user gets  price and currency for the totalprice on the checkout page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 32
 testRunner.Then("The price and currency for the totalprice on the bag page and on the checkout pag" +
                    "e should be equal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user compares totalprice and currency for order with discount code on the bag" +
            " page and on the checkout page")]
        [NUnit.Framework.CategoryAttribute("compareTotalPriceWithDiscount")]
        [NUnit.Framework.CategoryAttribute("bagPage")]
        [NUnit.Framework.CategoryAttribute("checkoutPage")]
        public virtual void TheUserComparesTotalpriceAndCurrencyForOrderWithDiscountCodeOnTheBagPageAndOnTheCheckoutPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user compares totalprice and currency for order with discount code on the bag" +
                    " page and on the checkout page", new string[] {
                        "compareTotalPriceWithDiscount",
                        "bagPage",
                        "checkoutPage"});
#line 35
this.ScenarioSetup(scenarioInfo);
#line 36
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 37
 testRunner.And("The user is on the bag page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.And("The user enters correct discount code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 39
 testRunner.And("The user gets price and currency for the totalprice on the bag page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 40
 testRunner.And("The user clicks the button \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 41
 testRunner.When("The user gets  price and currency for the totalprice on the checkout page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 42
 testRunner.Then("The price and currency for the totalprice on the bag page and on the checkout pag" +
                    "e should be equal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user compares discount percent and name for order on the bag page and on the " +
            "checkout page")]
        [NUnit.Framework.CategoryAttribute("compareDiscountPercent")]
        [NUnit.Framework.CategoryAttribute("bagPage")]
        [NUnit.Framework.CategoryAttribute("checkoutPage")]
        public virtual void TheUserComparesDiscountPercentAndNameForOrderOnTheBagPageAndOnTheCheckoutPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user compares discount percent and name for order on the bag page and on the " +
                    "checkout page", new string[] {
                        "compareDiscountPercent",
                        "bagPage",
                        "checkoutPage"});
#line 45
this.ScenarioSetup(scenarioInfo);
#line 46
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 47
 testRunner.And("The user is on the bag page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
 testRunner.And("The user enters correct discount code", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.And("The user gets discount percent and name for order on the bag page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
 testRunner.And("The user clicks the button \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
 testRunner.When("The user gets discount percent and name for order on the checkout page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 52
 testRunner.Then("The discount percent and name for order should be equal on the bag page and on th" +
                    "e checkout page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user verifies price for booklist on the bag page")]
        [NUnit.Framework.CategoryAttribute("verifyPriceBookList")]
        [NUnit.Framework.CategoryAttribute("bagPage")]
        public virtual void TheUserVerifiesPriceForBooklistOnTheBagPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user verifies price for booklist on the bag page", new string[] {
                        "verifyPriceBookList",
                        "bagPage"});
#line 55
this.ScenarioSetup(scenarioInfo);
#line 56
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 57
 testRunner.And("The user is on the bag page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.When("The user adds few books in the bag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
 testRunner.Then("The price for every book should be equal counted values", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user compares price for booklist on the bag page and on the checkout page")]
        [NUnit.Framework.CategoryAttribute("comparePriceBookList")]
        [NUnit.Framework.CategoryAttribute("bagPage")]
        [NUnit.Framework.CategoryAttribute("checkoutPage")]
        public virtual void TheUserComparesPriceForBooklistOnTheBagPageAndOnTheCheckoutPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user compares price for booklist on the bag page and on the checkout page", new string[] {
                        "comparePriceBookList",
                        "bagPage",
                        "checkoutPage"});
#line 62
this.ScenarioSetup(scenarioInfo);
#line 63
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 64
 testRunner.And("The user is on the bag page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 65
 testRunner.And("The user adds few books in the bag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 66
 testRunner.And("The user clicks the button \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 67
 testRunner.When("The user gets price for booklist on the checkout page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 68
 testRunner.Then("The price for booklist should be equal on the bag page and on the checkout page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user compares currency for totalprice on the bag page and on the checkout pag" +
            "e")]
        [NUnit.Framework.CategoryAttribute("compareCurrency")]
        [NUnit.Framework.CategoryAttribute("bagPage")]
        [NUnit.Framework.CategoryAttribute("checkoutPage")]
        [NUnit.Framework.CategoryAttribute("totalPrice")]
        public virtual void TheUserComparesCurrencyForTotalpriceOnTheBagPageAndOnTheCheckoutPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user compares currency for totalprice on the bag page and on the checkout pag" +
                    "e", new string[] {
                        "compareCurrency",
                        "bagPage",
                        "checkoutPage",
                        "totalPrice"});
#line 71
this.ScenarioSetup(scenarioInfo);
#line 72
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 73
 testRunner.And("The user is on the bag page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 74
 testRunner.And("The user adds few books in the bag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
 testRunner.And("The user gets currency from totalprice", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
 testRunner.And("The user clicks the button \"Next\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
 testRunner.When("The user gets currency for totalprice on the checkout page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 78
 testRunner.Then("The currency for totalprice should be equal on the bag page and on the checkout p" +
                    "age", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user compares price for the first book using different currency")]
        [NUnit.Framework.CategoryAttribute("comparePriceWithDifferentCurrency")]
        [NUnit.Framework.CategoryAttribute("bagPage")]
        public virtual void TheUserComparesPriceForTheFirstBookUsingDifferentCurrency()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user compares price for the first book using different currency", new string[] {
                        "comparePriceWithDifferentCurrency",
                        "bagPage"});
#line 81
this.ScenarioSetup(scenarioInfo);
#line 82
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 83
 testRunner.And("The user is on the bag page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
 testRunner.And("The user adds few books in the bag", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 85
 testRunner.When("The user changes currency for order", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 86
 testRunner.And("The user gets price for the first book", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 87
 testRunner.Then("The price for the first book with another currency should be as price from json f" +
                    "ile Currencies.json", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
