// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PencilJoyTests.BddCore.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Verify Reminder")]
    public partial class VerifyReminderFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Reminder.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Verify Reminder", "\tIn order to fill remind data on the preview page\r\n\tAs a customer\r\n\tThe user want" +
                    "s to be able to fill data for reminder with the letter", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user opens the popup \"Remind me later\" on the preview page")]
        [NUnit.Framework.CategoryAttribute("previewPage")]
        [NUnit.Framework.CategoryAttribute("openingPopup")]
        [NUnit.Framework.CategoryAttribute("positive")]
        public virtual void TheUserOpensThePopupRemindMeLaterOnThePreviewPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user opens the popup \"Remind me later\" on the preview page", new string[] {
                        "previewPage",
                        "openingPopup",
                        "positive"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.And("The user is on the preview page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.When("The user clicks the button \"Remind me later\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 11
 testRunner.Then("The popup \"Remind me later\" should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user closes the popup \"Remind me later\" on the preview page")]
        [NUnit.Framework.CategoryAttribute("previewPage")]
        [NUnit.Framework.CategoryAttribute("closingPopupRemindMeLater")]
        [NUnit.Framework.CategoryAttribute("positive")]
        public virtual void TheUserClosesThePopupRemindMeLaterOnThePreviewPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user closes the popup \"Remind me later\" on the preview page", new string[] {
                        "previewPage",
                        "closingPopupRemindMeLater",
                        "positive"});
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
 testRunner.And("The user is on the preview page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
 testRunner.And("The popup \"Remind me later\" should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 18
 testRunner.When("The user clicks the button \"X\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 19
 testRunner.Then("The popup \"Remind me later\" should be disappear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user closes the popup \"Your reminder is set\" on the preview page")]
        [NUnit.Framework.CategoryAttribute("previewPage")]
        [NUnit.Framework.CategoryAttribute("closingPopupYourReminderIsSet")]
        [NUnit.Framework.CategoryAttribute("positive")]
        public virtual void TheUserClosesThePopupYourReminderIsSetOnThePreviewPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user closes the popup \"Your reminder is set\" on the preview page", new string[] {
                        "previewPage",
                        "closingPopupYourReminderIsSet",
                        "positive"});
#line 22
this.ScenarioSetup(scenarioInfo);
#line 23
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 24
 testRunner.And("The user is on the preview page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 25
 testRunner.And("The popup \"Your reminder is set\" should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 26
 testRunner.When("The user clicks the button \"X\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 27
 testRunner.Then("The popup \"Your reminder is set\" should be disappear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user fills form for the letter reminder with all activated checkboxes")]
        [NUnit.Framework.CategoryAttribute("previewPage")]
        [NUnit.Framework.CategoryAttribute("55days")]
        [NUnit.Framework.CategoryAttribute("30days")]
        [NUnit.Framework.CategoryAttribute("newsAndSpecialDeals")]
        [NUnit.Framework.CategoryAttribute("positive")]
        public virtual void TheUserFillsFormForTheLetterReminderWithAllActivatedCheckboxes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user fills form for the letter reminder with all activated checkboxes", new string[] {
                        "previewPage",
                        "55days",
                        "30days",
                        "newsAndSpecialDeals",
                        "positive"});
#line 30
this.ScenarioSetup(scenarioInfo);
#line 31
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 32
 testRunner.And("The user is on the preview page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 33
 testRunner.And("The popup \"Remind me later\" should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 34
 testRunner.And("The user fills the field \"Your email\" with correct data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 35
 testRunner.And("The user clicks the checkbox \"55 days before December 25th\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 36
 testRunner.And("The user clicks the checkbox \"30 days before\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 37
 testRunner.And("The user clicks the checkbox \"Subscribe to news and special deals\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 38
 testRunner.When("The user clicks the button \"Set reminder\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 39
 testRunner.Then("The popup \"Remind me later\" should be disappear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 40
 testRunner.And("The popup \"Your reminder is set\" should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user fills form for the letter reminder before 55 days")]
        [NUnit.Framework.CategoryAttribute("55days")]
        [NUnit.Framework.CategoryAttribute("previewPage")]
        [NUnit.Framework.CategoryAttribute("positive")]
        public virtual void TheUserFillsFormForTheLetterReminderBefore55Days()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user fills form for the letter reminder before 55 days", new string[] {
                        "55days",
                        "previewPage",
                        "positive"});
#line 43
this.ScenarioSetup(scenarioInfo);
#line 44
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 45
 testRunner.And("The user is on the preview page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
 testRunner.And("The popup \"Remind me later\" should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
 testRunner.When("The user fills the field \"Your email\" with correct data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 48
 testRunner.And("The user clicks the checkbox \"55 days before December 25th\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
 testRunner.And("The user clicks the button \"Set reminder\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
 testRunner.Then("The popup \"Remind me later\" should be disappear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 51
 testRunner.And("The popup \"Your reminder is set\" should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user fills form for the letter reminder before 30 days")]
        [NUnit.Framework.CategoryAttribute("30days")]
        [NUnit.Framework.CategoryAttribute("previewPage")]
        [NUnit.Framework.CategoryAttribute("positive")]
        public virtual void TheUserFillsFormForTheLetterReminderBefore30Days()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user fills form for the letter reminder before 30 days", new string[] {
                        "30days",
                        "previewPage",
                        "positive"});
#line 54
this.ScenarioSetup(scenarioInfo);
#line 55
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 56
 testRunner.And("The user is on the preview page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 57
 testRunner.And("The popup \"Remind me later\" should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 58
 testRunner.When("The user fills the field \"Your email\" with correct data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 59
 testRunner.And("The user clicks the checkbox \"30 days before\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 60
 testRunner.And("The user fill date in the datepicker", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 61
 testRunner.And("The user clicks the button \"Set reminder\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 62
 testRunner.Then("The popup \"Remind me later\" should be disappear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 63
 testRunner.And("The popup \"Your reminder is set\" should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user compares email in the popups")]
        [NUnit.Framework.CategoryAttribute("verifyEmails")]
        [NUnit.Framework.CategoryAttribute("positive")]
        public virtual void TheUserComparesEmailInThePopups()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user compares email in the popups", new string[] {
                        "verifyEmails",
                        "positive"});
#line 66
this.ScenarioSetup(scenarioInfo);
#line 67
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 68
 testRunner.And("The user is on the preview page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 69
 testRunner.And("The popup \"Remind me later\" should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 70
 testRunner.And("The user fills the field \"Your email\" with correct data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 71
 testRunner.And("The user clicks the checkbox \"55 days before December 25th\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 72
 testRunner.When("The user clicks the button \"Set reminder\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 73
 testRunner.Then("The string in the popup \"Your reminder is set\" should exist email as was filling " +
                    "before", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user fills form for the letter without email")]
        [NUnit.Framework.CategoryAttribute("55days")]
        [NUnit.Framework.CategoryAttribute("previewPage")]
        [NUnit.Framework.CategoryAttribute("negative")]
        public virtual void TheUserFillsFormForTheLetterWithoutEmail()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user fills form for the letter without email", new string[] {
                        "55days",
                        "previewPage",
                        "negative"});
#line 76
this.ScenarioSetup(scenarioInfo);
#line 77
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 78
 testRunner.And("The user is on the preview page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
 testRunner.And("The popup \"Remind me later\" should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
 testRunner.When("The user clicks the checkbox \"55 days before December 25th\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 81
 testRunner.And("The user clicks the button \"Set reminder\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 82
 testRunner.Then("The fiels \"Your email\" should get red border", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 83
 testRunner.And("The popup \"Your reminder is set\" should not be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user fills form for the letter reminder before 30 days without selected date")]
        [NUnit.Framework.CategoryAttribute("30days")]
        [NUnit.Framework.CategoryAttribute("previewPage")]
        [NUnit.Framework.CategoryAttribute("negative")]
        public virtual void TheUserFillsFormForTheLetterReminderBefore30DaysWithoutSelectedDate()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user fills form for the letter reminder before 30 days without selected date", new string[] {
                        "30days",
                        "previewPage",
                        "negative"});
#line 86
this.ScenarioSetup(scenarioInfo);
#line 87
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 88
 testRunner.And("The user is on the preview page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 89
 testRunner.And("The popup \"Remind me later\" should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
 testRunner.And("The user fills the field \"Your email\" with correct data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 91
 testRunner.And("The user clicks the checkbox \"30 days before\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 92
 testRunner.When("The user clicks the button \"Set reminder\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 93
 testRunner.Then("The textbox for datepicker should get red border", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 94
 testRunner.And("The popup \"Your reminder is set\" should not be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user doesn`t checked any checkbox in the form for the letter reminder")]
        [NUnit.Framework.CategoryAttribute("previewPage")]
        [NUnit.Framework.CategoryAttribute("negative")]
        public virtual void TheUserDoesnTCheckedAnyCheckboxInTheFormForTheLetterReminder()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user doesn`t checked any checkbox in the form for the letter reminder", new string[] {
                        "previewPage",
                        "negative"});
#line 97
 this.ScenarioSetup(scenarioInfo);
#line 98
 testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 99
 testRunner.And("The user is on the preview page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 100
 testRunner.And("The popup \"Remind me later\" should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 101
 testRunner.And("The user fills the field \"Your email\" with correct data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 102
 testRunner.When("The user clicks the button \"Set reminder\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 103
 testRunner.Then("The block with the red text \"Please select any option below\" should be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 104
 testRunner.And("The popup \"Your reminder is set\" should not be appear", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
