// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PencilJoyTests.BddCore.Features.Checkout.Payment
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Choose PayPal payment on the checkout page")]
    public partial class ChoosePayPalPaymentOnTheCheckoutPageFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ChoosePayPalPayment.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Choose PayPal payment on the checkout page", "\tIn order to choose PayPal payment Billing Address\r\n\tAs a customer\r\n\tThe user wan" +
                    "ts to be able to choose PayPal payment", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user clicks tab for seing PayPal payment")]
        public virtual void TheUserClicksTabForSeingPayPalPayment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user clicks tab for seing PayPal payment", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
    testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
    testRunner.And("The user is on the checkout page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "UsernameB",
                        "LastnameB",
                        "StreetB",
                        "CityB",
                        "ZipCodeB",
                        "PhoneB",
                        "NumberCountryB",
                        "RegionB"});
            table1.AddRow(new string[] {
                        "Barbi",
                        "D\'orsay",
                        "3108 Northwestern",
                        "Panyambungan",
                        "43063-445",
                        "+62 (563) 802-6203",
                        "14",
                        "Malasin"});
#line 9
    testRunner.And("The user correct fills the fields for Billing Address as <UsernameB> <LastnameB> " +
                    "<StreetB> <CityB> <ZipCodeB> <PhoneB> <NumberCountryB> <RegionB>", ((string)(null)), table1, "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "UsernameS",
                        "LastnameS",
                        "StreetS",
                        "CityS",
                        "ZipCodeS",
                        "PhoneS",
                        "NumberCountryS",
                        "RegionS"});
            table2.AddRow(new string[] {
                        "Gerty",
                        "Eagles",
                        "13911 Everett Pass",
                        "Eslāmāb",
                        "0924-5701",
                        "+98 (540) 526-5197",
                        "12",
                        "Lumsden"});
#line 12
 testRunner.And("The user correct fills the fields for Shipping Address as <UsernameS> <LastnameS>" +
                    " <StreetS> <CityS> <ZipCodeS> <PhoneS> <NumberCountryS> <RegionS>", ((string)(null)), table2, "And ");
#line 15
 testRunner.When("The user clicks the tab PayPal in the Payment Data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 16
    testRunner.Then("The tab should show the button Check out with PayPal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("The user chooses PayPal payment")]
        public virtual void TheUserChoosesPayPalPayment()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("The user chooses PayPal payment", ((string[])(null)));
#line 18
this.ScenarioSetup(scenarioInfo);
#line 19
    testRunner.Given("The user is a customer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
    testRunner.And("The user is on checkout page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "UsernameB",
                        "LastnameB",
                        "StreetB",
                        "CityB",
                        "ZipCodeB",
                        "PhoneB",
                        "NumberCountryB",
                        "RegionB"});
            table3.AddRow(new string[] {
                        "August",
                        "Accomb",
                        "8 Grasskamp Trail",
                        "Kuroiso",
                        "0093-7206",
                        "+81 (504) 678-7207",
                        "3",
                        "Cucutilla"});
#line 21
    testRunner.And("The user correct fills the fields for Billing Address as <UsernameB> <LastnameB> " +
                    "<StreetB> <CityB> <ZipCodeB> <PhoneB> <NumberCountryB> <RegionB>", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "UsernameS",
                        "LastnameS",
                        "StreetS",
                        "CityS",
                        "ZipCodeS",
                        "PhoneS",
                        "NumberCountryS",
                        "RegionS"});
            table4.AddRow(new string[] {
                        "Grace",
                        "Chictto",
                        "115 Arizona Parkway",
                        "Langtang",
                        "36800-647",
                        "+234 (683) 231-9702",
                        "20",
                        "Gongju"});
#line 24
 testRunner.And("The user correct fills the fields for Shipping Address as <UsernameS> <LastnameS>" +
                    " <StreetS> <CityS> <ZipCodeS> <PhoneS> <NumberCountryS> <RegionS>", ((string)(null)), table4, "And ");
#line 27
 testRunner.And("The user clicks the tab PayPal in the Payment Data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 28
    testRunner.When("The user clicks the button Check out with PayPal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 29
    testRunner.Then("The page is redirected to PayPal service", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
